flowchart LR

subgraph start
end

subgraph env[Setting Environment Variables]
    direction TB
    isFlagNoEnvironSet{--no-environ}
    isEnvRenvironSet[/R_ENVIRON/]
    doesRenvironSiteExist[/R_HOME/etc/Renviron.site/]
    setEnvUser[Set environment variables]
    isEnvRenvironUserSet[/R_ENVIRON_USER/]
    doesProjectRenvironExist[/.Renviron/]
    doesUserRenvironExist[/"~/.Renviron"/]
    setEnvSystem[Set environment variables]
    endEnvSetup[End envvar set]

    isFlagNoEnvironSet --> |unset| isEnvRenvironSet
    isEnvRenvironSet --> |undefined| doesRenvironSiteExist
    doesRenvironSiteExist --> |DNE| isEnvRenvironUserSet
    isEnvRenvironUserSet --> |undefined| doesProjectRenvironExist
    doesProjectRenvironExist --> |DNE| doesUserRenvironExist

    isEnvRenvironSet & doesRenvironSiteExist ---> setEnvSystem
    setEnvSystem --> isEnvRenvironUserSet
    isEnvRenvironUserSet & doesProjectRenvironExist & doesUserRenvironExist ---> setEnvUser 
end

doesUserRenvironExist --> |DNE| endEnvSetup
isFlagNoEnvironSet --> |set| endEnvSetup
setEnvUser --> endEnvSetup

subgraph startup[Running Startup Scripts]
    direction TB
    isFlagNoSiteFileSet{--no-site-file}
    isEnvRprofileSet[/R_PROFILE/]
    doesRprofileSiteExist[/R_HOME/etc/Rprofile.site/]
    runScriptSystem[Run script]
    isFlagNoInitFileSet{--no-init-file}
    isEnvRprofileUserSet[/R_PROFILE_USER/]
    doesProjectRprofileExist[/.Rprofile/]
    doesUserRprofileExist[/"~/.Rprofile"/]
    runScriptUser[Run script]
    endStartupScripts[End startup scripts]

    isFlagNoSiteFileSet --> |set| isFlagNoInitFileSet
    isFlagNoSiteFileSet --> |unset| isEnvRprofileSet
    isEnvRprofileSet --> |undefined| doesRprofileSiteExist
    doesRprofileSiteExist --> |DNE| isFlagNoInitFileSet

    isEnvRprofileSet & doesRprofileSiteExist --> runScriptSystem --> isFlagNoInitFileSet
    isFlagNoInitFileSet --> |unset| isEnvRprofileUserSet
    isEnvRprofileUserSet & doesProjectRprofileExist & doesUserRprofileExist --> runScriptUser
    isEnvRprofileUserSet --> |undefined| doesProjectRprofileExist --> |DNE| doesUserRprofileExist
end

isFlagNoInitFileSet --> |set| endStartupScripts
doesUserRprofileExist --> |DNE| endStartupScripts
runScriptUser --> endStartupScripts

subgraph session[Setting Up Session]
    direction TB
    isFlagNoRestoreDataSet{--no-restore-data}
    doesProjectRDataExist[/.Rdata/]
    loadData[Load data]
    runDotFirst[[".First()"]]
    runBaseDotFirstSys[["base::.First.sys()"]]
    isFlagNoRestoreHistorySet{--no-restore-history}
    isEnvRHistifileSet[/R_HISTFILE/]
    doesProjectRhistoryExist[/.Rhistory/]
    loadHistory[Load history]
    endSessionSetup[End of Session Setup]

    isFlagNoRestoreDataSet --> |unset| doesProjectRDataExist
    isFlagNoRestoreDataSet --> |set| runDotFirst
    doesProjectRDataExist --> |DNE| runDotFirst
    doesProjectRDataExist --> loadData
    loadData --> runDotFirst --> runBaseDotFirstSys --> isFlagNoRestoreHistorySet
end

isFlagNoRestoreHistorySet --> |set| endSessionSetup
isFlagNoRestoreHistorySet --> |unset| isEnvRHistifileSet
isEnvRHistifileSet --> |undefined| doesProjectRhistoryExist
doesProjectRhistoryExist --> endSessionSetup
isEnvRHistifileSet & doesProjectRhistoryExist --> loadHistory --> endSessionSetup

subgraph running
end

start --> env
env --> startup
startup --> session
session --> running